// Inspired from https://blog.searce.com/build-machine-images-with-packer-on-google-cloud-platform-b43f77f1acd

variable "account_file" {
  type    = string
  default = "${env("GOOGLE_APPLICATION_CREDENTIALS")}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  account_file      = "${var.account_file}"
  image_description = "Web server for portfolio web app."
  image_labels = {
    developer = "rohan"
    team      = "cloud"
  }
  image_name              = "portfolio-web-app-${local.timestamp}"
  image_storage_locations = ["us-central1"]
  network                 = "packer-vpc"
  project_id              = "GCP_PROJECT_ID"
  service_account_email   = "packer-sa@gcp_project.iam.gserviceaccount.com"
  source_image_family     = "ubuntu-2004-lts"
  ssh_username            = "root"
  subnetwork              = "packer-vpc"
  zone                    = "us-central1-a"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    inline = ["mkdir -p /var/www/html"]
  }

  provisioner "file" {
    destination = "/var/www/html"
    source      = "public/"
  }

  provisioner "shell" {
    script = "deploy.sh"
  }

  post-processor "vagrant" {
  }

  post-processor "compress" {
    output = "portfolio-web-app-vagrant.tar.gz"
  }

  post-processor "googlecompute-export" {
    keep_input_artifact = true
    paths               = ["gs://gcs_bucket/portfolio-web-app-vagrant.tar.gz"]
  }
}
